* Tactile Glove software
** required dependencies
- boost::program_options
- boost::thread
- boost::regex

** optional dependencies
- Qt4 or Qt5 with QtSVG (for visualization)
- ncurses (for nice console output)
- ROS (for ROS publish/receive)

** Usage
The software is split in two parts: a console program and a GUI program (in corresponding sub dirs).

*** console
The console program supports two output modes
- console
- ROS topic /TactileGlove

and two input modes
- serial (real glove connected via USB)
- dummy  (provide random dummy values)

*** GloveViz GUI
The GUI program correspondingly supports several input modes, that are choosen on the command line:
- serial (real glove connected via USB)
- ROS topic /TactileGlove
- dummy  (provide random dummy values)

If no ROS/catkin environment is found during build, ROS support will be disabled.

As the glove comes in different variants, it's possible to chose the taxel layout 
as well as the mapping of taxels to individual data channels.
To this end, the GloveViz GUI uses svg files describing the layout and a taxel.cfg file
describing the mapping from svg node IDs to data channels. Both files are compiled into the binary.

As a glove layout might exist in different instantiations with different mappings,
the taxel.cfg file contains several sections, one for each known glove instantiation / mapping,
each referencing the corresponding layout. Hence, on the command line, you should simply choose
your glove version with option =-m version=. 

However, you can also specify your own or modify the existing mapping on the commandline,
either loading an own mapping file with option =-c mapping.ini= or specifying individual mapping like so: =name=channel=.
